name: Auto Counteng Authors

on:
  push:
    paths:
      - 'data/**'
  workflow_dispatch:

jobs:
  count-authors:
    runs-on: ubuntu-latest
    premissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/chechkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Counting Authors
        run: |
          echo "=== Подсчёт кол-во графов на автора ==="
          FILE="author-graphs.txt"
          printf 'Автор\tКол-во Графов\n' > "$FILE"
          COUNT_DIR="data"
          cd "$DIR" || exit

        find . -name "*.json" -exec grep -h '"author":' {} \; | \
        awk -F'"' '{print $4}' | sort | \
        uniq -c | \
        while read count author; do 
          printf "$author\t$count\n" >> "../$FILE"
        done


      - name: Commit and push
        run: |
          git config --global user.name 'githib-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data
          git commit -m "Auto-normalize graph files in data" || echo "Нет изменений для коммита"
          git push

